version: "3.9"

services:
  flask_app:
    container_name: flask_app
    image: flask-app:1.0
    build: .
    ports:
      - "5000:5000"
    environment:
      - "MYSQL_HOST:flask_db"
      - "MYSQL_USER:root"
      - "MYSQL_PASSWORD:password"
      - "MYSQL_DB:users_db"
#      - DB_URL=postgresql://postgres:postgres@flask_db:5432/postgres
#      - DB_URL=mysql://mysql:root@flask_db_mine:3360/users_db
    depends_on:
      - flask_db
  flask_db:
    container_name: flask_db
    image: flask-db-image-new:latest
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_USER:root"
      - "MYSQL_ROOT_PASSWORD:password"
      - "MYSQL_DATABASE:users_db"
    volumes:
      - my-flask-volume:/var/lib/mysql

volumes:
  my-flask-volume: {}
